### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by minmax100** [irsisyphus/reconet#1]
Nice work!

Any plan to release the training code?

**Comment by w1xmovies** [comment]
Amazing work and great adaptation. 
Still waiting for the code!

**Comment by safwankdb** [comment]
Check this out https://github.com/safwankdb/ReCoNet-PyTorch

**Comment by irsisyphus** [comment]
Thanks @safwankdb 
Please let me know if you have and trouble re-implementing the paper.

**Comment by safwankdb** [comment]
@irsisyphus I have some questions.
I used the coefficients for various losses as mentioned in the paper, but the magnitude of the losses was very different (difference of 7 orders of magnitude). Is this normal? Was there any change while adapting the perceptual losses from that paper?
