### ISSUE TITLE
Ask for pre-trained model.

### ISSUE THREAD

**Issue by daooshee** [irsisyphus/reconet#3]
Amazing work!
I notice that all the model binary files in `models/weights/` are empty. When do you plan to release the pre-trained code?

**Comment by irsisyphus** [comment]
See #1 for training code.

**Comment by ChristophWuersch** [comment]
Thank you very much for providing the pytorch implementation of the ReCoNet. It would be great if you could us provide a pretrained model. On my GPU I have too less memory to train the nets.
